services:
  dockerlock:
    image: derrickj11/dsci-522-group-project:1c69433
    ports:
      - "8888:8888"
    volumes:
      - ./:/work
    working_dir: /work
    container_name: dsci522_jupyter
    environment:
      - JUPYTER_TOKEN=dsci522
    command: start-notebook.py