name: 522_group_project_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - altair
  - pandera
  - jupyterlab
  - ipykernel
  - click
  - vl-convert-python
  - pytest         
  - pip
  - pip:
      - ucimlrepo
      - loguniform 